language: node_js
node_js:
  - 8
branches:
  only:
    - master
    - release
    - beta
    - /^greenkeeper/.*$/
install:
  - npm i 
  - npm run init
  - npm run build --prod
  - npm run test:ci
  - npm run coverage
