language: node_js
node_js:
  - 8
  - 9

branches:
  only:
    - master
    - release
    - beta
    - /^greenkeeper/.*$/
install:
  - npm i 
  - npm run init
  - npm run build --prod
  - npm run test:ci
  - npm run coverage
deploy:
  provider: npm
  email: "NPM_EMAIL"
  api_key: "NPM_AUTH_TOKEN"
script:
  - npm run publish:$TRAVIS_BRANCH
