# Fully Inspired by https://github.com/aws-amplify/amplify-js/blob/master/.circleci/config.yml

version: 2

aliases:
  - &restore-cache-deps
      key: v1-dependencies-update{{ checksum "package.json" }}
   
  - &save-cache-deps
      key: v1-dependencies-update{{ checksum "package.json" }}
      paths:
        - node_modules

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-browsers
      environment:
          ## this enables colors in the output
          TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-deps
      - run: rm -rf node_modules/
      - run: npm install npm@latest
      - run: npm install
      - run: lerna clean --yes
      - run: npm run init
      - save_cache: *save-cache-deps
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - "*"        
  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build --prod
      - run: npm run test:ci
      - run: npm run coverage
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache: *restore-cache-deps
      - run:
          name: "Publish O-RANGO Package"
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              git config --global user.email $GITHUB_EMAIL
              git config --global user.name $GITHUB_USER
              npm run publish:$CIRCLE_BRANCH
            else
              echo "Skipping deploy."
            fi
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - unit_test:
          requires:
            - build

      - deploy:
          filters:
            branches:
              only:
                - release
                - master
          requires:
            - unit_test
