/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface OI18n {}
  interface OI18nAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'OI18n': Components.OI18n;
  }

  interface StencilIntrinsicElements {
    'o-i18n': Components.OI18nAttributes;
  }


  interface HTMLOI18nElement extends Components.OI18n, HTMLStencilElement {}
  var HTMLOI18nElement: {
    prototype: HTMLOI18nElement;
    new (): HTMLOI18nElement;
  };

  interface HTMLElementTagNameMap {
    'o-i18n': HTMLOI18nElement
  }

  interface ElementTagNameMap {
    'o-i18n': HTMLOI18nElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
